# Generated by Django 4.2 on 2023-05-01 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myapp', '0003_alter_customer_state_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('kerala', 'kerala'), ('karnataka', 'karnataka'), ('tamilnadu', 'tamilnadu')], max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('ar', 'ACRYLIC'), ('pp', 'PAINT PALETTE'), ('cr', 'CANVAS ROLL'), ('pb', 'PAINTING BRUSH'), ('cb', 'CANVAS BOARD'), ('sb', 'SKETCH BOOK'), ('gh', 'GRAPHITE POWDER'), ('pk', 'PAINTING KNIFE'), ('gp', 'GRAPHITE PENCIL'), ('wc', 'WATERCOLOUR'), ('dp', 'DRAWING PAPER')], max_length=200),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
